# Generated by Django 3.0.7 on 2020-06-25 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, verbose_name='Enter Name of Event here: ')),
                ('event_duration', models.IntegerField(default=30, verbose_name='Enter duration in minutes: ')),
                ('event_date', models.DateField(verbose_name='set date here')),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
